// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjkxaspdtsxwksnoqdoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqa3hhc3BkdHN4d2tzbm9xZG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MDQxMDMsImV4cCI6MjA4OTE4MDEwM30.hxiWGI9b1BYMz5f6tbqImWaD1Ls7D_pYHBiwdxb6DWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});